#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "atuin"
name = "Atuin"
description.en = "Self-hosted Atuin for syncing and backing up encrypted shell history across devices"
description.fr = "Atuin, pour synchroniser et sauvegarder votre historique de shell chiffrÃ© entre vos appareils."

version = "18.11.0~ynh1"

maintainers = ["ximikos"]

[upstream]
license = "MIT"
website = "https://atuin.sh"
admindoc = "https://docs.atuin.sh/cli/self-hosting/server-setup/"
userdoc = "https://docs.atuin.sh/cli/"
code = "https://github.com/atuinsh/atuin"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/atuin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/atuinsh/atuin/releases/download/v18.11.0/atuin-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "f473f73fe9d2a0378fe2435a96d9da9d114df1c0edbb6bff88408ac157955c9a"
    arm64.url = "https://github.com/atuinsh/atuin/releases/download/v18.11.0/atuin-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "09ab168a1db71a22b906ab3497ce156b45b6d9a8274fc872c12d2fc365e99b0d"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^atuin-x86_64-unknown-linux-gnu\\.tar\\.gz$"
    autoupdate.asset.arm64 = "^atuin-aarch64-unknown-linux-gnu\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false

    [resources.ports]
